// include/config.h
#ifndef CONFIG_H
#define CONFIG_H

#include "common.h"

typedef struct {
int SIMULATION_DURATION;
int COUNTER_ESPIONAGE_AGENCY_MEMBER;
int RESISTANCE_GROUP_CREATION_INTERVAL;
int RESISTANCE_MEMBER_MIN;
int RESISTANCE_MEMBER_MAX;
int RESISTANCE_GROUP_MAX;
float MILITARY_GROUP_PROBABILITY;
float SPY_PROBABILITY;
float SUSPICION_THRESHOLD;
float SPY_CONFIRMATION_THRESHOLD;
float FULL_GROUP_KILLED_PROBABILITY;
float MIXED_OUTCOME_PROBABILITY;
float KILL_PROBABILITY;
float INJURY_PROBABILITY;
float CAPTURE_PROBABILITY;
int LIGHT_INJURY_RECOVERY_TIME;
float SEVERE_INJURY_PROBABILITY;
float ENEMY_ATTACK_PROBABILITY;
float AGENCY_MEMBER_TARGET_PROBABILITY;
int MAX_KILLED_MEMBERS;
int MAX_INJURED_MEMBERS;
int AGENCY_INACTIVITY_LIMIT;
int CIVILIAN_NUMBER;

} Config;

int load_config(const char *filename, Config *config);

#endif // CONFIG_H
